[package]
name = "millionlumenhomepage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "0.9.2", default-features = false }

[dev_dependencies]
soroban-sdk = { version = "0.9.2", features = ["testutils"] }

[features]
default = ["enumerable", "metadata"]
enumerable = []
metadata = []

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
