[package]
name = "erc721-example"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
erc721 = { workspace = true, default-features = false, features = ["metadata"] }
